name: tcp_client
description: |
  A simple client for TCP connections that manages connecting,
  reconnecting, sending, and receiving data to/from servers.
version: 0.1.0
homepage: https://www.jeffmikels.com

environment:
  sdk: '>=2.15.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
